spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/auction
    username: root
    password: shakee2001
  mail:
    host: smtp.gmail.com
    port: 587
    username: oraz20010101@gmail.com
    password: okixphxykvxuyctt
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false





